modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "shown"
version = "${version}"
displayName = "Shown"
authors = "GDPulsar"
description = '''
A widget-based UI system for Minecraft mods!
'''
#logoFile = ""

[[dependencies.shown]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shown]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shown]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "shown.mixins.json"
